services:
  api:
    build: ./go-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - POSTGRES=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
